// Fox Reader Frontend - TypeScript Types
// Mirrors src/fox_reader/models/requests.py

// ============================================================================
// Geometry
// ============================================================================

export interface Point {
    x: number;
    y: number;
}

export interface RectangleCoords {
    x: number;
    y: number;
    w: number;
    h: number;
}

export interface RectangleRegion {
    type: "rectangle";
    coords: RectangleCoords;
}

export interface PolygonRegion {
    type: "polygon";
    coords: Point[];
}

export type Region = RectangleRegion | PolygonRegion;

// ============================================================================
// API Request types
// ============================================================================

export interface FreeformRequest {
    filename: string;
    points: Point[];
    lang: string;
    isGrayScale: boolean;
}

export interface CropRequest {
    filename: string;
    x: number;
    y: number;
    width: number;
    height: number;
    lang: string;
    isGrayScale: boolean;
}

export interface BubbleRequest {
    filename: string;
    isGrayScale: boolean;
}

export interface SplitRequest {
    region: Region;
    split_object: Point[];
    isGrayScale: boolean;
    filename: string;
}

export interface TranslationRequest {
    text: string;
    source_lang: string;
    /** Custom endpoints send their id as `source_lang`; this carries the language. */
    lang_group?: string;
    /**
     * Earlier [[source, english], ...] pairs in reading order, sent only for
     * the local MTL endpoint when the Context switch is on. The backend uses
     * them solely when the loaded model renders context.
     */
    context?: [string, string][];
    /**
     * Character metadata for models that render it (VNTL). Sent only for the
     * local MTL endpoint when the Characters switch is on; ignored by every
     * other model. `character_info` is the roster snapshot,
     * `context_character_links` aligns to `context` by position (one meta_id
     * or null per pair), and `meta_id` names the speaker of `text`.
     */
    character_info?: CharacterInfo[];
    context_character_links?: (string | null)[];
    meta_id?: string | null;
}

/** One character in the roster. `meta_id` is generated by the backend. */
export interface CharacterInfo {
    meta_id: string;
    name_en?: string | null;
    name_ja?: string | null;
    gender?: string | null;
    alias_en?: string | null;
    alias_ja?: string | null;
}

/** Character fields as edited in the UI / CSV (no `meta_id`). */
export interface CharacterFields {
    name_en?: string;
    name_ja?: string;
    gender?: string;
    alias_en?: string;
    alias_ja?: string;
}

/**
 * Per-entry typesetting geometry. Mirrors the fields of the same name on
 * `DataItem` in `models/requests.py`; the ranges live in `fox_reader.typeset`
 * and are echoed by the `MIN_*`/`MAX_*` constants in `core/state.ts`.
 *
 * The two spacings are multipliers, with `null` meaning "leave that logic
 * alone"; the rest are neutral at their defaults, so an entry that never
 * touched them renders exactly as it did before they existed. Spacing and
 * scale take part in the auto font fit; the shift and the angles are applied
 * afterwards, to the lettering alone -- never to the plate behind it.
 */
export interface TextGeometry {
    /** Word gap, as a multiple of the face's own space advance. */
    word_spacing: number | null;
    /** Baseline distance, as a multiple of the natural line advance. */
    line_spacing: number | null;
    font_scale_x: number;
    font_scale_y: number;
    /** Post-fit nudge in image pixels, clamped so the ink stays on the page. */
    shift_x: number;
    shift_y: number;
    /** Post-fit rotation in degrees: X/Y tilt the plane, Z spins it clockwise. */
    angle_x: number;
    angle_y: number;
    angle_z: number;
}

export interface DataItem extends TextGeometry {
    og_text: string;
    text: string;
    fontfile: string;
    text_align: TextAlignment;
    points: [number, number][];
    /** 1 is the bottom layer; items are drawn low to high. */
    layer: number;
    /** `null` on any of these means "detect it from the image". */
    font_size: number | null;
    font_color: string | null;
    stroke_width: number | null;
    stroke_color: string | null;
    bg_mode: BgMode;
    bg_color: string | null;
    clean: CleanOptions | null;
}

export interface ProcessImageRequest {
    filename: string;
    data: DataItem[];
    /** Replace an existing file in the destination. Omitted means "no". */
    overwrite?: boolean;
}

export interface SavePreviewRequest {
    filename: string;
    token: string;
    /** Replace an existing file in the destination. Omitted means "no". */
    overwrite?: boolean;
}

export interface FolderRequest {
    path: string;
    /** Where typeset pages are written. Omitted lets the backend decide. */
    dest?: string;
    create_dest?: boolean;
}

export interface FolderInspectRequest {
    source: string;
    /** Empty or omitted asks the backend for its own suggestion. */
    dest?: string;
}

export interface LoadMLRequest {
    lang: string;
}

// ============================================================================
// API Response types
// ============================================================================

export interface TranslationResponse {
    original: string;
    translated: string;
    alt_translated: string;
    error?: string;
    translating?: boolean;
}

export interface OCRResponse {
    text: string;
}

export interface BubbleResponse {
    regions: Region[];
}

export interface FolderResponse {
    files: string[];
    /** Index-aligned with `files`: [width, height] per page; [0,0] if unreadable. */
    dimensions: [number, number][];
    /** The folder the pages were read from, as the backend resolved it. */
    source?: string;
    /** Where saving writes. Equal to `source` when saving in place. */
    dest?: string;
    same_dir?: boolean;
    /** Pages that already have a typeset copy in `dest`. Empty when same_dir. */
    saved?: string[];
}

/**
 * What one directory is and what we may do with it -- `fsaccess.DirReport`.
 *
 * `writable` is the result of a real create-and-delete probe on the backend, not
 * an `os.access` guess, so it can be shown to the user as fact.
 */
export interface DirReport {
    path: string;
    exists: boolean;
    is_dir: boolean;
    is_file: boolean;
    readable: boolean;
    writable: boolean;
    executable: boolean;
    /** Only filled in for the source; `null` means "not counted". */
    image_count: number | null;
    parent: string;
    parent_exists: boolean;
    parent_writable: boolean;
    /** The first blocking problem, already phrased for display. */
    reason: string;
    can_create: boolean;
    ok_as_source: boolean;
    ok_as_dest: boolean;
}

export interface FolderInspectResponse {
    status: string;
    source: DirReport;
    dest: DirReport;
    /** `<source>/fox_tled`. */
    default_dest: string;
    /** What this source was loaded with last time, or "". */
    remembered_dest: string;
    same_dir: boolean;
}

export interface FolderStateResponse {
    status: string;
    source: string;
    dest: string;
    same_dir: boolean;
    saved: string[];
    last_source: string;
    default_dest_name: string;
}

export interface FontInfo {
    name: string;
    file: string;
    priority: number;
}

/** One text-clean method, and why it may not be usable right now. */
export interface CleanMethodInfo {
    id: CleanMethod;
    label: string;
    available: boolean;
    reason: string;
    /** Tuning controls this method reads. Absent on an older backend. */
    knobs?: CleanKnob[];
}

/** One detector speed preset, with what it costs. */
export interface CleanSpeedInfo {
    value: string;
    label: string;
    /** Forward passes, at most -- the inverted pass is skipped on a light page. */
    passes: number;
    /** Whether this preset has flip averaging for the TTA switch to turn off. */
    tta: boolean;
}

/** One tile size, with the overlap the backend pairs it with. */
export interface CleanTileInfo {
    value: number;
    label: string;
    overlap: number;
}

export interface CleanMethodsResponse {
    methods: CleanMethodInfo[];
    /** Reconstruction methods, as reported by `fox_reader.clean.INPAINT_METHODS`. */
    fills: string[];
    default_fill: string;
    /** Detector presets, slowest first. Absent on an older backend. */
    speeds?: CleanSpeedInfo[];
    default_speed?: string;
    default_tta?: boolean;
    tiles?: CleanTileInfo[];
    default_tile?: number;
}

/** A snapshot of a long backend job, polled from /api/progress/{name}. */
export interface ProgressSnapshot {
    name: string;
    running: boolean;
    message: string;
    lines: string[];
    done: number;
    total: number;
    elapsed?: number;
    error?: string | null;
    idle?: boolean;
    /** Present once a preview has finished; identifies the saveable artifact. */
    token?: string;
}

/** A rendered preview: the image, plus the token that lets it be saved as-is. */
export interface PreviewResult {
    blob: Blob;
    token: string;
}

/** One active user-defined endpoint, as served by /api/user_endpoints/active. */
export interface ActiveCustomEndpoint {
    id: string;
    name: string;
    url: string;
    method: string;
}

export interface ActiveCustomEndpointsResponse {
    active: Record<string, ActiveCustomEndpoint[]>;
    max_active_per_language?: number;
}

// ============================================================================
// State types
// ============================================================================

/** How text is set inside its region. Mirrors `typeset.TEXT_ALIGNMENTS`. */
export type TextAlignment = "left" | "center" | "right";

/** How an entry's region is treated before its text is drawn. */
export type BgMode = "auto" | "color" | "transparent" | "clean";

/** Where text-clean gets the shape it removes. */
export type CleanMethod = "region" | "ppocr" | "textseg";

/**
 * Which tuning controls a clean method actually reads.
 *
 * Sent per method by /api/clean/methods so the panel offers only knobs that do
 * something: `glow` under PaddleOCR would be a lie, since box coverage has no
 * halo to absorb. `fill` and `transport` are not listed -- they belong to the
 * reconstruction stage and apply to every method, `region` included.
 */
export type CleanKnob = "glow" | "speed" | "tta" | "tile";

export interface CleanOptions {
    method: CleanMethod;
    /** One of `fox_reader.clean.INPAINT_METHODS`. */
    fill: string;
    glow: boolean;
    transport: boolean;
    /** A preset in `fox_reader.clean.SPEEDS`: how many forward passes to spend. */
    speed: string;
    /** Flip averaging. Only `best` has any for this to switch off. */
    tta: boolean;
    /** One of `fox_reader.clean.TILE_OVERLAPS`; 0 predicts the crop whole. */
    tile: number;
}

export type TranslatorProvider = "deepl" | "jpdb" | "ml" | "custom";

export type TranslateEndpoint = `/translate/${TranslatorProvider}`;

export type CaptureMode = "rect" | "freeform" | "bubble" | null;

// ============================================================================
// Event types
// ============================================================================

export interface EventMap {
    "image:loaded": [string];
    /**
     * A *different* page is now on screen.
     *
     * Distinct from `image:loaded`, which also fires when the same page is
     * re-fitted or re-fetched. Listen here for the things that belong to one
     * page and must not follow the reader to the next -- the captured text, its
     * translation, the last region.
     */
    "page:changed": [string];
    "entries:render": [];
    "gallery:navigate": [number];
    /** Translator buttons were added or removed after the initial render. */
    "translators:changed": [];
    /** Strip (webtoon) mode was toggled or reset; reader controls should re-render. */
    "strip:changed": [];
}

// ============================================================================
// Window augmentation for inline HTML onclick handlers
// ============================================================================

declare global {
    interface Window {
        loadLocalFolder: () => void;
        showLoading: (text?: string) => void;
        hideLoading: () => void;
        showNotify: (msg: string) => void;
        cycleTextAlignment: () => void;
        updateActionRow: () => void;
        confirmCurrentTranslation: () => void;
        clearCurrentPageEntries: () => Promise<void>;
        executeInpaintAction: (mode: "preview" | "generate") => void;
        pageCapture: () => void;
        addNewEntries: (data: Region[], force?: boolean) => void;
        renderCurrentPageEntries: (source?: string) => void;
        navigateGallery: (dir: number) => void;
        startCapture: () => void;
        startFreeCapture: () => void;
        bubbleCapture: () => void;
        toggleFontDropdown: () => void;
        closeInpaintModal: () => void;
        saveInpaintPreview: () => void;
        __selectFontOption: (filename: string, fontName: string, cssFamily: string) => void;
        __checkMarquee: (el: HTMLElement) => void;
        __stopMarquee: (el: HTMLElement) => void;
    }
}
